# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e27d1e1de77d53dd50f1692af862b70a3a3cb67c87ab3d370fdf464e47f8755f581afa3a0c930a879c43e1293b08acc33e25f38337289c2c88f806844c46f83

test:
  secret_key_base: d25023657462b959ff4b9e332a38821545dd1edaae9d44e7fce04e036957bda4bb86aab52eb1d889ebd4cb61c372d9a682de5bbb8f241f8910fd25a32d20ee77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
